package com.aws.carddemo.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;

/**
 * Add-transaction request, mirroring COTRN02C (add transaction). The transaction id is
 * generated by the service if not supplied.
 */
public record TransactionCreateDto(
        @NotBlank String tranCardNum,
        @NotBlank String tranTypeCd,
        @NotNull Integer tranCatCd,
        String tranSource,
        String tranDesc,
        @NotNull BigDecimal tranAmt,
        Long tranMerchantId,
        String tranMerchantName,
        String tranMerchantCity,
        String tranMerchantZip,
        String tranOrigTs) {
}
