#!/usr/bin/env bash
#
# init_user_security.sh - Bootstrap the user-security store with
# SHA-256 hashed passwords sourced from a secure secret store.
#
# The script supports two outputs:
#   1. The legacy 160-byte VSAM record format (PS file uploaded to the
#      mainframe before STEP01 of ESDSRRDS.jcl).
#   2. The modernised relational `user_security` table defined in
#      db/schema.sql.
#
# Plaintext passwords are NEVER written to disk in either path.

set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: init_user_security.sh <output-mode> <output-path>

  output-mode  ps   - write the 160-byte fixed-width PS file (used by
                       ESDSRRDS.jcl).
                sql  - write a SQL INSERT script targeting the
                       user_security table defined in db/schema.sql.

Environment variables (all required):
  SECRET_BACKEND       secretsmanager | ssm | vault | env
  CARDDEMO_ADMIN_PWD   plaintext password used to hash for the bootstrap
                       admin accounts (sourced from the secret store)
  CARDDEMO_USER_PWD    plaintext password used to hash for the bootstrap
                       regular-user accounts

The SECRET_BACKEND selection determines how CARDDEMO_ADMIN_PWD and
CARDDEMO_USER_PWD are resolved:

  secretsmanager   aws secretsmanager get-secret-value
  ssm              aws ssm get-parameter --with-decryption
  vault            vault kv get
  env              read directly from the environment (CI / dev only)
USAGE
    exit 1
}

[[ $# -ne 2 ]] && usage

mode="$1"
out_path="$2"
backend="${SECRET_BACKEND:-env}"

resolve_secret() {
    local logical_name="$1"
    case "$backend" in
        secretsmanager)
            aws secretsmanager get-secret-value \
                --secret-id "$logical_name" \
                --query SecretString --output text
            ;;
        ssm)
            aws ssm get-parameter \
                --name "$logical_name" --with-decryption \
                --query 'Parameter.Value' --output text
            ;;
        vault)
            vault kv get -field=value "secret/data/${logical_name}"
            ;;
        env)
            local env_var
            env_var=$(echo "$logical_name" | tr 'a-z/' 'A-Z_')
            printf '%s' "${!env_var:-}"
            ;;
        *)
            echo "ERROR: unsupported SECRET_BACKEND=$backend" >&2
            exit 2
            ;;
    esac
}

admin_pwd="${CARDDEMO_ADMIN_PWD:-$(resolve_secret carddemo/admin/password)}"
user_pwd="${CARDDEMO_USER_PWD:-$(resolve_secret carddemo/user/password)}"

if [[ -z "$admin_pwd" || -z "$user_pwd" ]]; then
    echo "ERROR: bootstrap passwords not found in secret store ($backend)" >&2
    exit 3
fi

# 10 demo accounts identical to the ones seeded by ESDSRRDS.jcl.
# Real deployments should drive this from a CSV or a directory service.
declare -a accounts=(
    "ADMIN001|MARGARET|GOLD|A|ADMIN001SALT0001"
    "ADMIN002|RUSSELL|RUSSELL|A|ADMIN002SALT0002"
    "ADMIN003|RAYMOND|WHITMORE|A|ADMIN003SALT0003"
    "ADMIN004|EMMANUEL|CASGRAIN|A|ADMIN004SALT0004"
    "ADMIN005|GRANVILLE|LACHAPELLE|A|ADMIN005SALT0005"
    "USER0001|LAWRENCE|THOMAS|U|USER0001SALT0001"
    "USER0002|AJITH|KUMAR|U|USER0002SALT0002"
    "USER0003|LAURITZ|ALME|U|USER0003SALT0003"
    "USER0004|AVERARDO|MAZZI|U|USER0004SALT0004"
    "USER0005|LEE|TING|U|USER0005SALT0005"
)

# Compute SHA-256(password || salt) as lowercase hex.  Uses python's
# hashlib so the script has no external dependencies beyond the
# standard library.
hash_password() {
    local password="$1"
    local salt="$2"
    python3 - "$password" "$salt" <<'PY'
import sys, hashlib
print(hashlib.sha256((sys.argv[1] + sys.argv[2]).encode("utf-8")).hexdigest())
PY
}

write_ps() {
    local out="$1"
    : > "$out"
    for row in "${accounts[@]}"; do
        IFS='|' read -r uid fname lname utype salt <<< "$row"
        case "$utype" in
            A) plain="$admin_pwd" ;;
            *) plain="$user_pwd" ;;
        esac
        digest=$(hash_password "$plain" "$salt")
        # Layout: 8/20/20/8/1/23/64/16 = 160 bytes
        printf '%-8s%-20s%-20s%-8s%-1s%-23s%-64s%-16s\n' \
            "$uid" "$fname" "$lname" "" "$utype" "" "$digest" "$salt" \
            >> "$out"
    done
    echo "Wrote $(wc -l < "$out") records to $out"
}

write_sql() {
    local out="$1"
    {
        echo '-- Generated by init_user_security.sh'
        echo '-- Plaintext passwords are NEVER stored.'
        echo 'BEGIN;'
        echo "DELETE FROM user_security WHERE user_id IN ($(printf "'%s'," "${accounts[@]%%|*}" | sed 's/,$//'));"
        for row in "${accounts[@]}"; do
            IFS='|' read -r uid fname lname utype salt <<< "$row"
            case "$utype" in
                A) plain="$admin_pwd" ;;
                *) plain="$user_pwd" ;;
            esac
            digest=$(hash_password "$plain" "$salt")
            printf "INSERT INTO user_security (user_id, first_name, last_name, user_type, password_hash, password_salt) VALUES ('%s', '%s', '%s', '%s', '%s', '%s');\n" \
                "$uid" "$fname" "$lname" "$utype" "$digest" "$salt"
        done
        echo 'COMMIT;'
    } > "$out"
    echo "Wrote SQL bootstrap to $out"
}

case "$mode" in
    ps)  write_ps "$out_path" ;;
    sql) write_sql "$out_path" ;;
    *)   usage ;;
esac
